[package]
name = "sof-chargen"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-map =  { version = "2.7.3", features = ["serde"] }
rand = "0.9.1"
serde = { version = "1.0.216", features = ["derive"] }
subenum = "1.1.2"